Listningtour/Controllers/PayPalController.cs
using Listningtour.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Listningtour.Controllers
{
    public class PayPalController : Controller
    {

        DataClasses1DataContext dba = new DataClasses1DataContext();

        //[Authorize(Roles="Customers")]
        public ActionResult ValidateCommand(string product, string totalPrice)
        {
            bool useSandbox = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSandbox"]);


            var paypal = new PayPalModel(useSandbox);


            //var user = Session["LoggedInUser"] as User;
            //if (user != null)
            //{
            //    paypal.UserId = user.Id;
            //}


            paypal.item_name = product;
            paypal.amount = totalPrice;

            //dba.Paypaldatas.InsertOnSubmit(paypal);
            //dba.SubmitChanges();

            return View(paypal);

        }


        public ActionResult RedirectFromPaypal()
        {
            PublishedProperty obj = new Models.PublishedProperty();
            var user = Session["LoggedInUser"] as User;
            obj.UserId = user.Id;
            obj.PublishedUrl = "";
            dba.PublishedProperties.InsertOnSubmit(obj);
            dba.SubmitChanges();
            Session["PublishedId"] = obj.Id;
            return RedirectToAction("Steps1", "MultiSteps");
        }

        public ActionResult CancelFromPaypal()
        {
            return View();
        }

        public ActionResult NotifyFromPaypal()
        {
            return View();
        }



        public ActionResult Payment()
        {
            return View();
        }









    }
}

Listningtour/Views/PayPal/CancelFromPaypal.cshtml
@{
    ViewBag.Title = "CancelFromPaypal";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}



<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="comment_set">
                <h3>
                    Cancel From Paypal

                </h3>
            </div>
        </div>
    </div>
</div>

Listningtour/Views/PayPal/NotifyFromPaypal.cshtml
@{
    ViewBag.Title = "NotifyFromPaypal";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}



<body>

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="comment_set">
                    <h3>
                        NotifyFromPaypal..
                    </h3>
                </div>
            </div>
        </div>
    </div>

</body>

Listningtour/Views/PayPal/Payment.cshtml
@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}



@using (Html.BeginForm("ValidateCommand", "PayPal"))
{
    <div class="new_form">
        <div class="container">
            <div class="row" style="margin:130px">
               
                <div class="col-md-3">
                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="WEH4F7XX8MY66">
                        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                        <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                    </form>
                </div>
                @*<div class="col-md-6">
                    <div class="form_set">*@
                       
                        @*<table>
                            <tr>
                                <td>
                                    Product Name:
                                </td>
                                <td>
                                    <input type="text" name="product" value="Listning Tour" readonly />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Total Price $:
                                </td>
                                <td>
                                    <input type="text" name="totalPrice" value="25" readonly />
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="my_btn">
                                    <input type="submit" name="btnConfirm" value="Check Out with Paypal" />
                                </td>
                            </tr>
                        </table>*@
                    @*</div>
                </div>*@
            </div>
        </div>
    </div>
}

Listningtour/Views/PayPal/RedirectFromPaypal.cshtml
@{
    ViewBag.Title = "RedirectFromPaypal";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<body>
   
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="comment_set">
                    <h3>
                        RedirectFromPaypal
                    </h3>
                </div>
            </div>
        </div>
    </div>

</body>

Listningtour/Views/PayPal/ValidateCommand.cshtml
@model Listningtour.Models.PayPalModel
@{
    ViewBag.Title = "ValidateCommand";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}




<body>
    <form id="hiddenform" action=@Model.actionURL>
        @Html.HiddenFor(model => model.cmd)
        @Html.HiddenFor(model => model.business)
        @Html.HiddenFor(model => model.no_shipping)
        @Html.HiddenFor(model => model.@return)
        @Html.HiddenFor(model => model.cancel_return)
        @Html.HiddenFor(model => model.notify_url)
        @Html.HiddenFor(model => model.currency_code)
        @Html.HiddenFor(model => model.item_name)
        @Html.HiddenFor(model => model.amount)
    </form>

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="comment_set">
                    <h3>
                        Connecting to Paypal please wait ...

                    </h3>
                </div>
            </div>
        </div>
    </div>

</body>

@*@Scripts.Render("~/bundles/jquery")*@

<script type="text/javascript" language="javascript">
    $(this.document).ready(function () {
        var form = $("form");
        form.submit();
    });
</script>