Listningtour/Controllers/MultiStepsController.cs
using Listningtour.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using static Listningtour.Core.Infrastructure.SecurityFunction;

namespace Listningtour.Controllers
{
    public class MultiStepsController : Controller
    {
        DataClasses1DataContext dba = new DataClasses1DataContext();

        // GET: MultiSteps
        public ActionResult Steps1(string Propertytype, string Typesofhome,  string Type = "")
        {

            if (Session["LoggedInUser"] == null)
            {
                return RedirectToAction("Login", "Account");
            }


            if (Type != "")
            {
                return View("Steps1");
            }

            var userPropertyData = GetSessionData<UserPropertyViewModel>("UserProperty");
            if (userPropertyData == null)
            {
                var data = GetUserPopertyPreview();
                SetSessionData("UserProperty", data);

                userPropertyData = data;
            }
            return View("Steps1", userPropertyData);
        }

        private void SetSessionData<T>(string key, T data)
        {
            Session[key.ToUpper()] = data;
        }

        private T GetSessionData<T>(string key)
        {
            if (Session[key.ToUpper()] == null)

                return default(T);

            else

                return (T)Session[key.ToUpper()];
        }


        private void ClearAllSteps()
        {

            Session.Remove("Steps1");
            Session.Remove("Steps2");
            Session.Remove("Steps3");
        }


        [HttpPost]
        public ActionResult Steps1(string Propertytype, string Typesofhome, UserPropertyViewModel Data)
        {
            var loggedInUserr = Session["LoggedInUser"] as User;
            if (loggedInUserr == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                var viewModelData = GetSessionData<UserPropertyViewModel>("UserProperty");

                if (viewModelData != null)
                {
                    Data.Images = viewModelData.Images;
                }
                SetSessionData("UserProperty", Data);
                return RedirectToAction("Steps2", viewModelData);

            }
            return View(Data);
        }




        /// <param name="files"></param>
        /// <returns></returns>
        /// 
        [HttpGet]
        public ActionResult Steps2()
        {

            var viewModelData = GetSessionData<UserPropertyViewModel>("UserProperty");
            return View(viewModelData);
        }

        [HttpPost]
        public ActionResult Steps2(IEnumerable<HttpPostedFileBase> file, string Type = "")
        {
            var loggedInUserr = Session["LoggedInUser"] as User;
            if (loggedInUserr == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                var firstStepViewModel = GetSessionData<UserPropertyViewModel>("UserProperty");
               // var viewModelData = GetSessionData<UserPropertyViewModel>("UserProperty");
                if(firstStepViewModel.Images==null)
                {
                    firstStepViewModel.Images = new List<ImageViewModel>();
                }
                else
                {
                    firstStepViewModel.Images = firstStepViewModel.Images;// new List<ImageViewModel>();
                }
              
                // firstStepViewModel.Images = new List<ImageViewModel>();
                var imgList = new List<ImageViewModel>();

                var URL = "";
                foreach (var item in file)
                {
                    if (item != null && item.ContentLength > 0)
                    {
                        try
                        {
                            string path = Path.Combine(Server.MapPath("~/Images"), Path.GetFileName(item.FileName));
                            item.SaveAs(path);
                            URL = CommonCls.GetURL() + "/Images/" + item.FileName;
                            //thumbnail


                            // Session["FileName"] = URL;
                            var objImg = new ImageViewModel();
                            objImg.PhotoPath = URL;
                            objImg.thumbnails = "";

                            imgList.Add(objImg);

                        }

                        catch (Exception ex)
                        {
                            ViewBag.Message = "ERROR:" + ex.Message.ToString();
                        }

                    }

                }
                if(imgList.Count()>0)
                {
                    firstStepViewModel.Images.AddRange(imgList);
                }
               
               SetSessionData("UserProperty", firstStepViewModel);
                User myUser = Session["LoggedInUser"] as User;// User myUser = (User)Session["LoggedInUser"];
                var user = dba.Userinfos.Where(c => c.UserId == Convert.ToInt32(myUser.Id)).FirstOrDefault();
                if (user != null)
                {
                    UserProfile usr = new UserProfile();
                    usr.Name = user.Name;
                    usr.Middlename = user.Middlename;
                    usr.Lastname = user.Lastname;
                    usr.Email = user.Email;
                    usr.Website = user.Website;
                    usr.Designation = user.Designation;
                    usr.PhotoPath = user.PhotoPath;
                    usr.CompanyLogo = user.CompanyLogo;
                    usr.CellNo = user.CellNo;

                    firstStepViewModel.User = usr;
                }
                return RedirectToAction("Steps3", firstStepViewModel);
            }

            return View();

        }

        [HttpGet]
        public ActionResult Steps3()
        {
            var loggedInUserr = Session["LoggedInUser"] as User;
            if (loggedInUserr == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var viewModelData = GetSessionData<UserPropertyViewModel>("UserProperty");
            //Adress adrs = new Adress();
            //adrs.Address = viewModelData.PropertyAddress;
            //adrs.GeoCode();
            //string lat = adrs.Latitude;
            //string lng = adrs.Longitude;
            //StringBuilder sb = new StringBuilder();
            //DataSet ds = GetWalkingScore1(viewModelData.PropertyAddress, lat, lng);
            //if (ds.Tables.Count > 0)
            //{
            //    //imgg.ImageUrl = ds.Tables[0].Rows[0]["logo_url"].ToString();
            //    viewModelData.WalkScore = ds.Tables[0].Rows[0]["walkscore"].ToString();

            //    // lblwalk.PostBackUrl = "http://www.walkscore.com/score/loc/lat=" + lat + "/lng=" + lng + "/?utm_source=http://roccobuyandsell.com&amp;utm_medium=ws_api&amp;utm_campaign=ws_api";

            //}
            return View(viewModelData);
        }


        [HttpPost]
        public ActionResult Steps3(UserPropertyViewModel data)
        {

            var loggedInUserr = Session["LoggedInUser"] as User;
            if (loggedInUserr == null)
            {
                return RedirectToAction("Login", "Account");
            }

            //  TempData["Fullurl"] = HttpContext.Request.Url.AbsoluteUri;

            var viewModelData = GetSessionData<UserPropertyViewModel>("UserProperty");
            var user = Session["LoggedInUser"] as User;
            if (user != null)
            {
                viewModelData.UserId = user.Id;
            }
            Step stepToSave = null;
            if (viewModelData.Stepid > 0)
            {
                stepToSave = dba.Steps.FirstOrDefault(c => c.UserId == viewModelData.Stepid);
            }

            stepToSave = stepToSave ?? new Step();

            stepToSave.PropertyAddress = viewModelData.PropertyAddress;
            stepToSave.Price = viewModelData.Price;
            stepToSave.Washrooms = viewModelData.Washrooms;
            stepToSave.Bedrooms = viewModelData.Bedrooms;
            stepToSave.Area = viewModelData.Area;
            stepToSave.Status = viewModelData.Status;
            stepToSave.Propertytype = viewModelData.Propertytype;
            stepToSave.Typesofhome = viewModelData.Typesofhome;
            stepToSave.MLS = viewModelData.MLS;
            stepToSave.YoutubeLink = viewModelData.YoutubeLink;
            stepToSave.UserId = viewModelData.UserId;

            if (viewModelData.Stepid == 0)
            dba.Steps.InsertOnSubmit(stepToSave);
            var images = dba.Images.Where(c => c.UserId == viewModelData.UserId).ToList();

            if (images != null && images?.Count != viewModelData.Images?.Count)
            {
                foreach (var img in images)
                    dba.Images.DeleteOnSubmit(img);

                foreach (var img in viewModelData.Images)
                {
                    dba.Images.InsertOnSubmit(new Image
                    {
                        UserId = stepToSave.UserId.GetValueOrDefault(),
                        PhotoPath = img.PhotoPath,
                        thumbnails = img.thumbnails,
                        Step = stepToSave
                    });
                }

            }
            else if (images != null && images?.Count == viewModelData?.Images?.Count && viewModelData?.Images?.Count > 0)
            {
                int idx = 0;
                foreach (var img in images)
                {
                   // img.UserId = stepToSave.UserId.GetValueOrDefault();
                    img.PhotoPath = viewModelData.Images[idx].PhotoPath;

Listningtour/Views/Dashboard/Index.cshtml
@model Listningtour.Models.Dto.DashboardData

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}



<div class="dashboard--wrapper">
    <div class="container">
        <div class="dashboard-area">
            <div class="row">
                <div class="d-upper ">
                    <div class="col-md-5">
                        <div class="d-pic animated  bounceInLeft">                         
                                @if (Model.PhotoPath == null || Model.PhotoPath == "")
                                {
                                    <img src="~/assets/img/profile-cover.jpg" style="height:50%;width:50%" />
                                }
                                else
                                {
                                    <img src=@Model.PhotoPath  alt="profile-img" class="img-thumbnail img-responsive" style="height:50%;width:50%" />
                                }

                                <i class="fa fa-user hide"></i>
                            
                         
                            <h1>
                                <tr>
                                    <td>@Html.DisplayFor(x => x.Name)</td> <td>@Html.DisplayFor(x => x.Middlename)</td> <td>@Html.DisplayFor(x => x.Lastname)</td>
                                </tr>
                            </h1>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="d-btn animated  bounceInRight">
                            <ul class="list-inline">                         
                                @*<li><button type="button" onclick="location.href='@Url.Action("Steps1","MultiSteps",new { Type = "CreateTour" })'">Create Tour</button></li>*@


                                <li><button type="button" onclick="location.href='@Url.Action("payment","Dashboard")'">Create Tour</button></li> 
                                
                                                                                                                                                                                
                                @*<li><button type="button" onclick="location.href='@Url.Action("Steps1","MultiSteps")'">CreateTour</button></li>*@      
                                
                                                                                                                                                                             
                                <li><button type="button" onclick="location.href='@Url.Action("Edit","Dashboard", new { Userinfoid = Model.Userinfoid })'">Edit Profile</button></li>
                           </ul>
                        </div>




                    </div>
                </div>
            </div>

            <div class="d_main">
                <div class="row">
                    <div class="col-md-5">
                        <!---TABLE--->
                        <div class="d-table">
                            <table class="table table-hover">

                                <tbody>
                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.City)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.City)</td>
                                    </tr>
                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.Email)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.Email)</td>
                                    </tr>
                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.Zipcode)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.Zipcode)</td>
                                    </tr>
                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.Designation)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.Designation)</td>
                                    </tr>
                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.CellNo)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.CellNo)</td>
                                    </tr>
                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.Brokerage)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.Brokerage)</td>
                                              
                                    </tr>

                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.OfficeAddress)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.OfficeAddress)</td>
                                    </tr>



                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.OfficeNo)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.OfficeNo)</td>
                                    </tr>

                                   

                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.Website)</th>
                                        <td>@Html.DisplayFor(modelItem => Model.Website)</td>
                                    </tr>
                                        <th>@Html.DisplayNameFor(model => model.CompanyLogo)</th>
                                        <td>
    <div class="animated">
        @if (Model.CompanyLogo == null || Model.CompanyLogo == "")
        {
            <img src="~/assets/img/profile-cover.jpg" style="height:50%;width:50%" />
        }
        else
        {
            <img src=@Model.CompanyLogo alt="profile-img" class="img-thumbnail img-responsive" style="height:30%;width:30%" />
        }

    </div>

</td>

                                    <tr>
                                    
                                </tbody>
                            </table>
                        </div>

                    </div>

                 

                    <div class="col-md-7">
                        <div class="dt_right">
                            <h3>Latest Tour Links</h3>
                            @if(Model.PublishedProperties.Count()>0)
                            {

                            <div class="d-table">
                                <table class="table table-hover">

                                    <tbody>
                                        <tr>
                                            <td>S.NO</td>
                                            <td>Property Address</td>
                                            <td>Tour Links</td>
                                        </tr>
                                        @{
                                            var count = 0;
                                            foreach (var item in @Model.PublishedProperties)
                                            {
                                                count++;
                                                <tr>
                                                    <th>@count</th>
                                                    <td>@item.Address</td>
                                                    <td>@item.ProperyUrl</td>
                                                </tr>

                                            }

                                        }

                                    </tbody>
                                </table>

                            </div>

                                            }
                                            else
                                            {
                                                <img src="" />
                                            }
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

Listningtour/Views/Dashboard/payment.cshtml
@model Listningtour.Models.Dto.DashboardData

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}



<div class="dashboard--wrapper">
    <div class="container">
        <div class="dashboard-area">
            <div class="row">
                <div class="d-upper ">
                    <div class="col-md-5">
                        <a href="https://www.paypal.com/invoice/p/#ZQKPCFBGJQLG4ZWZ">Pay</a>
                        @*<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                            <input type="hidden" name="cmd" value="_s-xclick">
                            <input type="hidden" name="hosted_button_id" value="WEH4F7XX8MY66">
                            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                        </form>*@
                    </div>

                </div>
            </div>


        </div>
    </div>
</div>